# Generated by Django 4.1 on 2022-08-10 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('gmaps', models.CharField(max_length=400)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=100)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.location')),
            ],
        ),
    ]
