# Generated by Django 4.1 on 2022-08-09 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_location_name_alter_restaurant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
    ]
